dev/РК-1
frontend-park-mail-ru/2023_2_AdDo pull request #1
Opened 2023-10-02 16:55 UTC by ambushidozho

2023-10-03 10:17 UTC, KrasavtsevSs requested changes

2023-10-03 10:17 UTC, KrasavtsevSs commented on dist/assets/css/app.css
Папку dist не нужно коммитить и хранить в репозитории

2023-10-03 10:17 UTC, Krasava872 commented on package.json
> +    "body-parser": "^1.20.0",
Этот пакет нельзя, убираем пишем логику сами)

2023-10-03 10:17 UTC, Krasava872 commented on package.json
> +    "cookie-parser": "^1.4.6",
Этот тоже)

2023-10-03 10:17 UTC, Krasava872 commented on package.json
> +    "debug": "^4.3.4",
И это

2023-10-03 10:17 UTC, Krasava872 commented on src/components/Feed/Feed.hbs
> +                <img class="contentPhoto" src="http://82.146.45.164:9000{{this.Preview}}" alt="1">
А если адрес хоста измениться?

2023-10-03 10:17 UTC, Krasava872 commented on src/components/Feed/Feed.js
> +export class Feed {
Если решил писать на классах, то лучше будет описать общий класс родитель, и использовать методы через прототипное наследование и контекст

2023-10-03 10:17 UTC, Krasava872 commented on src/components/Header/Header.css
Не понял задумки с именами в селекторах, где то будто нотации БЭМ, а где то просто CamelCase

2023-10-03 11:25 UTC, ambushidozho commented on src/components/Header/Header.css
Переделал всё в CamelCase

2023-10-03 11:25 UTC, ambushidozho commented on src/components/Feed/Feed.js
> +export class Feed {
Написал родительский общий класс

2023-10-03 11:25 UTC, ambushidozho commented on src/components/Feed/Feed.hbs
> +                <img class="contentPhoto" src="http://82.146.45.164:9000{{this.Preview}}" alt="1">
Вынес в отдельную переменную

2023-10-03 11:28 UTC, ambushidozho commented on package.json
> +    "body-parser": "^1.20.0",
А эти пакеты после лекции встали, они вроде и неиспользуются нигде.

2023-10-03 11:29 UTC, ambushidozho commented on package.json
> +    "cookie-parser": "^1.4.6",
удалил их

2023-10-03 11:29 UTC, ambushidozho commented on package.json
> +    "debug": "^4.3.4",
и этот тоже удалил

2023-10-04 12:55 UTC, Krasava872 approved these changes

2023-10-04 12:56 UTC, merged